### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by jlpilogistics** [sandervanhooft/laravel-invoicable#10]
I'm having some issue when entering 4 digits amount into invoice_lines. An error occurred, "A non well formed numeric value encountered".

**Comment by jlpilogistics** [comment]
more than 4 digits

**Comment by sandervanhooft** [comment]
That error is probably thrown by the number formatter.

Are you sure you’re using an integer (cents), and not a decimal or string?

**Comment by sandervanhooft** [comment]
See [here](
https://github.com/sandervanhooft/laravel-invoicable/blob/53c6ea975b48e4cad1b0ca41c6c723837e5a0004/src/MoneyFormatter.php#L33)

**Comment by jlpilogistics** [comment]
![image](https://user-images.githubusercontent.com/40427603/45110764-c3426b00-b175-11e8-8fc1-f3b18082ef0f.png)
Laravel highlights this one whenever i get the error

**Comment by sandervanhooft** [comment]
I’m a bit occupied at the moment, can you provide a failing test? And what php version are you on?

**Comment by sandervanhooft** [comment]
I'm going to close this for now. Let me know if there's any news.
