### ISSUE TITLE
Bad tax calculation in addAmountInclTax Method

### ISSUE THREAD

**Issue by platformsfx** [sandervanhooft/laravel-invoicable#11]
## Detailed description

In class Invoice.php, method addAmountIncTax, you're making the tax calculation like this: 
'tax' => $amount - $amount / (1 + $taxPercentage)

while it should be like this: 
'tax' => $amount * $taxPercentage,

## Context

It's important because this is a bad calculation !

## Possible implementation

change this line: 'tax' => $amount - $amount / (1 + $taxPercentage)
with this: 'tax' => $amount * $taxPercentage

## Your environment

Laravel 5.7

**Comment by sandervanhooft** [comment]
@platformsfx Thank you for opening this issue.

I get where you're coming from, but the current implementation is correct - perhaps it's not working as you expect. Let me see if I can clarify it a bit.

To clarify the differences between `addAmountInclTax` and `addAmountExclTax`, the readme includes examples resulting in the same numbers, but with different `$amount` inputs. Make sure to use the correct one for your scenario.

```php
// To add a line to the invoice, use these example parameters:
//  Amount:
//      121 (€1,21) incl tax
//      100 (€1,00) excl tax
//  Description: 'Some description'
//  Tax percentage: 0.21 (21%)
$invoice = $invoice->addAmountInclTax(121, 'Some description', 0.21); // tax is already included in the amount you pass in
$invoice = $invoice->addAmountExclTax(100, 'Some description', 0.21); // tax is not included in the amount you pass in

// Invoice totals are now updated
echo $invoice->total; // 242
echo $invoice->tax; // 42
```

For `addAmountExclTax` you would be right, that would use `['tax' => $amount * $taxPercentage]`. And it does. (So perhaps this is the one you need for your scenario.)

For `addAmountInclTax` the `$amount` you're passing in **_already contains the tax_**. To derive the tax from this requires the slightly more complex calculation `['tax' => $amount - $amount / (1 + $taxPercentage)]`.

Here's an overview (input parameters in **bold**):

| Method | Amount excl tax | Tax rate | Tax | Amount incl tax |
| ------ | ------ | ------ | ------ | ------ |
| `addAmountExclTax(100, "...", 0.21)` | **100** | **0.21** | 21 = 100 x 0.21 | 121 = 100 + 21 |
| `addAmountInclTax(121, "...", 0.21)` | 100 = 121 - 121 / (1 + 0.21) | **0.21** | 21 | **121**
