### ISSUE TITLE
Installation doesn't work - on publishing migrations

### ISSUE THREAD

**Issue by PovilasKorop** [sandervanhooft/laravel-invoicable#2]
This command

`$ php artisan vendor:publish --provider="SanderVanHooft\Invoicable\InvoicableServiceProvider" --tag="migrations"
`
doesn't work.

Filename is incorrect:
```
        // Publish migrations
         $this->publishes([
             __DIR__.'/../database/migrations/2017_06_17_163005_create_invoices_table.php'
             => database_path('migrations/2017_06_17_163005_create_invoices_table.php'),
         ], 'migrations');

```

Versus folder contents:

<img width="1003" alt="screen shot 2017-07-03 at 8 46 39 am" src="https://user-images.githubusercontent.com/1510147/27779513-2f97a290-5fcc-11e7-9b7c-0e3ad1007005.png">

**Comment by sandervanhooft** [comment]
@PovilasKorop Thanks for bringing that up. The filename should indeed be `..._invoices_tables.php` instead of `..._invoices_table.php`. I'll patch it.

**Comment by sandervanhooft** [comment]
Patched. Thanks @PovilasKorop !
