### ISSUE TITLE
What is invoicable_id?

### ISSUE THREAD

**Issue by movepixels** [sandervanhooft/laravel-invoicable#23]
What is this supposed to be?
I see the db table BIGINT(20) but I can never fill it with anything.

```
$data = [
      'invoicable_id' => $profile->id,
      'tax' => 0.00,
      'total' => 100.00,
      'receiver_info' => 'its to you',
      'sender_info' => 'its from me',
      'payment_info' => 'who knows',
      'note' => 'Some note',
    ];
$order = new Order();
$invoice = $order->invoices()->create($data);
```

Results in:
Integrity constraint violation: 1048 Column 'invoicable_id' cannot be null.

Fails when trying to insert the record into invoices table.

Any ideas?

Thanks,

Dave

**Comment by movepixels** [comment]
I have tried a combo of the snips below from reading thru issues posted.

```
$order = new Order();
$order->save();
$invoice = $order->invoices()->create([]);
```
or
```
try {
  $order   = new Order();
  $order->save();
  $invoice = $order->invoices()->create([]);
}
catch (\Exception $exception){
  echo $exception->getMessage();
}
```
or
```
$order = new Order();
$order->save();
```

And nothing.

The only thing that works in terms of creating an invoice is:
```
$order = new Order();
    $invoice = $order->invoices()->updateOrCreate(
      ['invoicable_id' => $profile->id],
      $data
    );
```
But then it always makes a new invoice and not updates the original one, so this makes the invoice, so yes that works, then I now have duplicate exact invoices so in the end it does not work.

Any help would be appreciated.

Laravel 5.7 forgot to mention.

**Comment by sandervanhooft** [comment]
The `invoicable_id` will be automatically filled with the Order id.

In this case the Order is an Eloquent model. You need to save it before creating the invoice (otherwise the Order has no id yet).

**Comment by movepixels** [comment]
But how?

```
$order = new Order();
$order->save();
```

Equals
General error: 1364 Field 'invoicable_type' doesn't have a default value (SQL: insert into `invoices` (`id`, `updated_at`, `created_at`) values (bdff553a-e2c6-11e9-8665-40167eb29fbd, 2019-09-29 14:38:03, 2019-09-29 14:38:03))

**Comment by sandervanhooft** [comment]
That error does not match the operation you're performing. Please provide complete code samples which allow to recreate the problem if you require help.

**Comment by movepixels** [comment]
Order.php model

```
<?php 

namespace App\Models\Billing;

use Illuminate\Database\Eloquent\Model;
use SanderVanHooft\Invoicable\IsInvoicable\IsInvoicableTrait;

class Order extends \App\Models\BaseModel{
  use IsInvoicableTrait;
  protected $table = 'invoices';
  public $incrementing = true;
  protected $fillable = ['*'];
  protected $hidden = [];
}
```

CompletionController.php snip 
I have multiple commented out code blocks as I have tried everything and none of them work.
```
<?php 

namespace App\Http\Controllers\Dashboard\Wizard;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Illuminate\Http\Response as HttpResponse;

// Models
use App\Models\Profile;
use App\Models\Billing\Order;

class CompletionController extends Controller {
  
  public function index(Profile $profile)
  {
    /*$order = new Order();
    $order->save();*/

    /*$order = new Order();
    $order->save();*/
    //$invoice = $order->invoices()->create();

    /*try {
      $order   = new Order();
      $order->save();
      $invoice = $order->invoices()->create([]);
    }
    catch (\Exception $exception){

      echo $exception->getMessage();
    }*/

    /*$order = new Order();
    $order->save();
    // $invoice = $invoice->addAmountInclTax(121, 'Some description', 0.21);
    */
    
    // $order = Order::create();

    /*$order = new Order();
    $invoice = $order->invoices()->updateOrCreate(
      ['invoicable_id' => $profile->id],
      $data
    );*/

    //$invoice = $order->invoices()->create($data);
    

    //$invoice = $invoice->addAmountInclTax(121, 'Some description', 0.21);
    //$invoice = $invoice->addAmountExclTax(100, 'Some description', 0.21);

    $response = [
      'user' => $profile->user,
      'profile' => $profile,
    ];

    return response()->json($response);
  }
```

So not sure why none of them work.

**Comment by movepixels** [comment]
I have UUID id for invoices table, so before changing id to CHAR(36)
I get this.

```
Warning: 1265 Data truncated for column 'id' at row 1 (SQL: insert into `invoices` (`id`, `updated_at`, `created_at`) values (47db0c82-e311-11e9-85f5-40167eb29fbd, 2019-09-29 23:31:37, 2019-09-29 23:31:37))
```

So I make the invoices.id field CHAR(36), run same function.

Then get a different error:
```
General error: 1364 Field 'invoicable_type' doesn't have a default value (SQL: insert into `invoices` (`id`, `updated_at`, `created_at`) values (9e5aba62-e311-11e9-b029-40167eb29fbd, 2019-09-29 23:34:02, 2019-09-29 23:34:02))
```

No no clue what so ever.

And thats trying this code:
```
$order = new Order();
$order->save();
$invoice = $order->invoices()->create([]);
```

**Comment by sandervanhooft** [comment]
This line on the Order model is probably tripping things up:

```php
protected $table = 'invoices';
```

**Comment by movepixels** [comment]
There is no actual "orders" table. I just followed your example where you say "Add the invoicable trait to the Eloquent model which needs to be invoiced (typically an Order model):"

Should there be an orders table in addition to the 2 tables (invoices, invoice_lines) your code creates?

I figured an Order and Invoice are the same thing. Am I wrong?

**Comment by sandervanhooft** [comment]
Yes. This package only handles generating the invoice. Order handling is outside scope (it's not the same thing).

**Comment by movepixels** [comment]
Ok, just curious. Maybe I was misunderstanding from the start hence the confusion. But is an order not the same as as an invoice just saying it as  a different term/adjective. 

So I make an order, 2 burgers 2 fries so order has order_items then make an invoice with invoice_lines 2 burger 2 fries? Is that not just repeating the same thing?

I will play around with it.

**Comment by movepixels** [comment]
Yes I had it all wrong in my head. 
Orders are what the user selects and creates / add / removes updates qty. 
They place that order. 
Invoice is created by business and given to customer of what was ordered, we delivered and billed charged /owed :)

**Comment by sandervanhooft** [comment]
Thanks for following up @movepixels ! Good to know it's all cleared up now :).
