### ISSUE TITLE
How do we add discounts to an invoice?

### ISSUE THREAD

**Issue by smoizs** [sandervanhooft/laravel-invoicable#4]
Great package, but I was unable to find a method to add a discount. This is more of an enhancement I think, but a feature that may be necessary.

Also, just like Tax, would be great to know how to add a discount before tax and after tax.

**Comment by sandervanhooft** [comment]
Hi @smoizs ,

Good point about the discount. It's described in the [blog article](https://www.sandervanhooft.com/blog/laravel/stop-creating-your-laravel-invoices-manually/), but somehow I forgot to mention it in the docs:

> You can handle discounts by adding a line with a negative amount, or describe it in the line description field (“product x incl 30% discount”) and subtract the discount manually.

I am able to handle all my discounting needs with this solution.
