### ISSUE TITLE
[DOC] Error on creating invoice pdf using the Readme example

### ISSUE THREAD

**Issue by banstola** [sandervanhooft/laravel-invoicable#7]
Hi,
I followed all the steps that you described and I ran the example that you have posted at Readme and I got the following error.

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'invoicable_id' cannot be null 
(SQL: insert into `invoices` 
(`invoicable_id`, `invoicable_type`, `currency`, `status`, `reference`, `updated_at`, `created_at`)
 values (, App\Invoices, EUR, concept, 2018-06-24-3P2L4M, 2018-06-24 15:27:15, 2018-06-24 15:27:15))
```
Following is the code 

```
       try {
                $order   = new Orders();
                $invoice = $order->invoices()->create([]);
            }
            catch (\Exception $exception){

                echo $exception->getMessage();
            }
```
Contexts
----------------
php 7.2 
latest version of this library
laravel - 5.6 
----------------

So I was wondering what is the correct procedure to create the invoice?

**Comment by sandervanhooft** [comment]
Hi @banstola ,

The `$order` doesn't seem to have an `id` set. This is generated on save.

In your example, try this:
```
$order   = new Orders();
$order->save();
$invoice = $order->invoices()->create([]);
```

**Comment by sandervanhooft** [comment]
A shortcut for this would be `$order = Order::create();`.

Another solution, if you don't want to use a related (Order) model, is to replace the `$table->morphs(...)` with `$table->nullableMorphs(...)` in the invoice migration. Don't forget to rerun the migration.

**Comment by banstola** [comment]
Hi @sandervanhooft ,

Thank you for the quick response. Will try it this evening and let you know. Maybe we need to improve the doc then. It would be easy for others to use that example and get an idea about it quickly.

**Comment by sandervanhooft** [comment]
@banstola Agreed! Feel free to submit a PR for the readme.

**Comment by banstola** [comment]
@sandervanhooft May I know the reason behind the need to create a separate Order model . Could it be that an invoice itself is an order . Invoice has invoice lines. What is the idea behind `invoicable_id`?

**Comment by sandervanhooft** [comment]
In every use case I have encountered with this package, the invoice was related to some other model. It could be a Order model, or the User model for example. That's why it has a polymorphic relationship by default.

Again, you can change this in the migration ([this comment](https://github.com/sandervanhooft/laravel-invoicable/issues/7#issuecomment-399876634)).

I am working on a v2 of this package, and I think it's interesting to use the `nullableMorphs` there by default. But it will probably take a few months.
